### PR TITLE
added library containing Boundary_pT

### PR DESCRIPTION
**Pull request by Mathadon**
This is the first pull request for #1 . More to follow as agreed.

### CODE REVIEW

**Comment by Mathadon** [comment]
@dhblum @mwetter Please check whether you agree with the library name.

**Comment by mwetter** [comment]
I am not thrilled about IBPSAMPC as people are not likely to be able to understand what this means. Maybe IBPSA_MPC or IbpsaMpc would be better, although the first looks like an experimental package as was done for Modelica_Fluid before it became official.

**Comment by Mathadon** [comment]
@dhblum IbpsaMpc is ok for me. If you agree then I'll adjust the PR.

**Comment by Mathadon** [comment]
@dhblum can you check this? Thanks!

**Comment by dhblum** [comment]
@Mathadon, IbpsaMpc is ok for me as well.  Sorry for the delay.

**Comment by dhblum** [comment]
@Mathadon Please also do not wait for me to merge this PR when it is edited based on the discussion above, as I will be on vacation, returning 8/19.

**Pull request merged**
