### PR TITLE
Add UsersGuide.Acknowledgements

### PR DESCRIPTION
**Pull request by dhblum**
For https://github.com/ibpsa/modelica-ibpsa-mpc/issues/6.

### CODE REVIEW

**Comment by dhblum** [comment]
@Mathadon Can you add any support acknowledgements for yourself?

**Review by mwetter — APPROVED** [review]

**Comment by Mathadon** [comment]
@dhblum will do

**Comment by dhblum** [comment]
@Mathadon Just a reminder so we can close this.

**Comment by Mathadon** [comment]
@dhblum done!

**Pull request merged**
